version: "3.9"

services:
  books:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "DMITRIEVA_205"
      POSTGRES_USER: "DMITRIEVA_205"
      POSTGRES_PASSWORD: "DMITRIEVA_205"
    volumes:
      - ./docker/db/scripts/books.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"

  railways:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "DMITRIEVA_205"
      POSTGRES_USER: "DMITRIEVA_205"
      POSTGRES_PASSWORD: "DMITRIEVA_205"
    volumes:
      - ./docker/db/scripts/railways.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

  hospital:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "DMITRIEVA_205"
      POSTGRES_USER: "DMITRIEVA_205"
      POSTGRES_PASSWORD: "DMITRIEVA_205"
    volumes:
      - ./docker/db/scripts/hospital.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"